title = "Abel Soares Siqueira"
baseURL = "https://abelsiqueira.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Abel Soares Siqueira"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Abel Soares Siqueira"
  favicon = "/images/icon.png"
  # site_logo = "/images/logo.png"
  description = "Personal and professional information"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  recent_posts_number = 3
  custom_css = ["extra.css"]

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/abel_siqueira"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/abelsiqueira"
[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/abel-siqueira"
[[params.ananke_socials]]
name = "mastodon"
url = "https://mathstodon.xyz/@abelsiqueira"
rel = "me noopener"
[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/siqueiraabel"
[[params.ananke_socials]]
name = "youtube"
url = "https://youtube.com/@abelsiqueira"
